-- AlterTable
ALTER TABLE "BreedLevel" ALTER COLUMN "bonusRate" SET DEFAULT 0,
ALTER COLUMN "bonusRate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "BreedPair" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION;
